# coding: utf-8

"""
    Ours

    The Ours Server-Side REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@oursprivacy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oursprivacy_client.models.identify_request import IdentifyRequest

class TestIdentifyRequest(unittest.TestCase):
    """IdentifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentifyRequest:
        """Test IdentifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentifyRequest`
        """
        model = IdentifyRequest()
        if include_optional:
            return IdentifyRequest(
                token = '0',
                user_id = '0',
                user_properties = oursprivacy_client.models.identify_request_user_properties.identify_request_userProperties(
                    email = '', 
                    first_name = '', 
                    last_name = '', 
                    gender = '', 
                    date_of_birth = '', 
                    phone_number = null, 
                    city = '', 
                    state = '', 
                    zip = null, 
                    country = '', 
                    external_id = '', 
                    company_name = '', 
                    job_title = '', 
                    ip = '', ),
                default_properties = oursprivacy_client.models.track_request_default_properties.track_request_defaultProperties(
                    is_bot = True, 
                    ad_id = '', 
                    encoding = '', 
                    browser_name = '', 
                    browser_version = '', 
                    cpu_architecture = '', 
                    device_type = '', 
                    device_model = '', 
                    device_vendor = '', 
                    engine_name = '', 
                    engine_version = '', 
                    os_name = '', 
                    os_version = '', 
                    browser_language = '', 
                    current_url = '', 
                    webview = True, 
                    iframe = True, 
                    session_count = 1.337, 
                    active_duration = 1.337, 
                    duration = 1.337, 
                    epik = '', 
                    sacid = '', 
                    fbc = '', 
                    fbclid = '', 
                    fbclid_creation_time = 1.337, 
                    fbp = '', 
                    gad_source = '', 
                    gbraid = '', 
                    gc_id = '', 
                    gclid = '', 
                    rdt_cid = '', 
                    host = '', 
                    ip = '', 
                    msclkid = '', 
                    li_fat_id = '', 
                    pathname = '', 
                    referrer = '', 
                    screen_height = 1.337, 
                    screen_width = 1.337, 
                    title = '', 
                    user_agent = '', 
                    user_agent_full_list = '', 
                    utm_campaign = '', 
                    utm_content = '', 
                    utm_medium = '', 
                    utm_name = '', 
                    ttclid = '', 
                    utm_source = '', 
                    utm_term = '', 
                    version = '', 
                    wbraid = '', )
            )
        else:
            return IdentifyRequest(
                token = '0',
                user_id = '0',
                user_properties = oursprivacy_client.models.identify_request_user_properties.identify_request_userProperties(
                    email = '', 
                    first_name = '', 
                    last_name = '', 
                    gender = '', 
                    date_of_birth = '', 
                    phone_number = null, 
                    city = '', 
                    state = '', 
                    zip = null, 
                    country = '', 
                    external_id = '', 
                    company_name = '', 
                    job_title = '', 
                    ip = '', ),
        )
        """

    def testIdentifyRequest(self):
        """Test IdentifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
