# coding: utf-8

"""
    Ours

    The Ours Server-Side REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@oursprivacy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oursprivacy_client.models.track_request_user_properties import TrackRequestUserProperties

class TestTrackRequestUserProperties(unittest.TestCase):
    """TrackRequestUserProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackRequestUserProperties:
        """Test TrackRequestUserProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackRequestUserProperties`
        """
        model = TrackRequestUserProperties()
        if include_optional:
            return TrackRequestUserProperties(
                email = '',
                first_name = '',
                last_name = '',
                gender = '',
                date_of_birth = '',
                phone_number = None,
                city = '',
                state = '',
                zip = None,
                country = '',
                external_id = '',
                company_name = '',
                job_title = '',
                ip = ''
            )
        else:
            return TrackRequestUserProperties(
        )
        """

    def testTrackRequestUserProperties(self):
        """Test TrackRequestUserProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
