# coding: utf-8

"""
    Ours

    The Ours Server-Side REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@oursprivacy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oursprivacy_client.models.track200_response import Track200Response

class TestTrack200Response(unittest.TestCase):
    """Track200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Track200Response:
        """Test Track200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Track200Response`
        """
        model = Track200Response()
        if include_optional:
            return Track200Response(
                success = True
            )
        else:
            return Track200Response(
                success = True,
        )
        """

    def testTrack200Response(self):
        """Test Track200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
