# coding: utf-8

# flake8: noqa

"""
    Ours

    The Ours Server-Side REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@oursprivacy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from oursprivacy_client.api.ours_privacy_api import OursPrivacyApi

# import ApiClient
from oursprivacy_client.api_response import ApiResponse
from oursprivacy_client.api_client import ApiClient
from oursprivacy_client.configuration import Configuration
from oursprivacy_client.exceptions import OpenApiException
from oursprivacy_client.exceptions import ApiTypeError
from oursprivacy_client.exceptions import ApiValueError
from oursprivacy_client.exceptions import ApiKeyError
from oursprivacy_client.exceptions import ApiAttributeError
from oursprivacy_client.exceptions import ApiException

# import models into sdk package
from oursprivacy_client.models.identify_request import IdentifyRequest
from oursprivacy_client.models.identify_request_user_properties import IdentifyRequestUserProperties
from oursprivacy_client.models.track200_response import Track200Response
from oursprivacy_client.models.track_request import TrackRequest
from oursprivacy_client.models.track_request_default_properties import TrackRequestDefaultProperties
from oursprivacy_client.models.track_request_user_properties import TrackRequestUserProperties
